1단계 - 장바구니(상품 목록)
next-step/android-shopping-cart pull request #15
Opened 2024-08-15 01:59 UTC by minhyukseul

안녕하세요~
이번 미션 잘 부탁드리겠습니다!

2024-08-15 08:16 UTC, laco-dev requested changes
장바구니 미션동안 잘 부탁드립니다.

현재 화면에 그려지는 리스트가 정상적으로 그려지지 않고 있어요.
공식문서를 참고해서 학습이 필요 해 보입니다.

조금 어렵게 느껴지신다면, 다른 분들이 작성하신 코드를 참고 해보셔도 됩니다.

2024-08-15 08:16 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +            .height(IntrinsicSize.Min)
IntrinsicSize 속성은 어떤 이유로 추가되었을까요?
자식의 높이가 무언가 잘못 설정되지는 않았을까요?

2024-08-15 08:16 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                fontSize = 16.sp,
머티리얼 테마를 사용하면 여러가지 텍스트 스타일을 간단하게 적용할 수 있습니다.
```kotlin
style = MaterialTheme.typography.xxx
...
```

2024-08-15 08:16 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +}
`"%,d".format(...)` 형태를 생각하신게 맞나요?

2024-08-15 08:16 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/TitleScreen.kt
> +package nextstep.shoppingcart.ui.screen
TitleScreen의 screen 패키지 이름과 파일 이름 기준은 어떻게 만드셨는지 알 수 있을까요?

2024-08-15 08:16 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                }
실제 앱을 실행해보시면, 스크롤이 동작을 하지 않습니다.

그 이유는 LazyColumn이 정상적으로 만들어지지 않았기 때문인데요.
또한 시안을 참고하면 2열의 Grid 형태가 지원되어야 합니다.

아래 문서를 참고하셔서 지연 목록에 대한 학습을 선행 해보시면 좋을 것 같아요.
https://developer.android.com/develop/ui/compose/lists?hl=ko#lazy-grids

2024-08-16 00:02 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +}
정확한 용어가 기억이 나진 않는데 참조하고 있는 함수를 읽기 좋기 하기 위해서 선언 아래쪽으로 가게 하는 방식으로 작업을 했는데 Preview의 경우에는 컨벤션이 이렇게 되어 있나 보군요! 감사합니다.

2024-08-16 00:03 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +            .height(IntrinsicSize.Min)
해당 속성은 Column의 height를 유동적으로 변경하기 위해서 사용을 해본건데요. xml의 wrap_content느낌으로요. 무언가 잘못되었을까요?

2024-08-16 00:03 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                fontSize = 16.sp,
style로 적용해서 사용하는 방식으로 한번 수정을 해보겠습니다!

2024-08-16 00:04 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +}
동작상 이슈가 있을까요? 한국(원)을 표시하기 위한 함수이긴 합니다.

2024-08-16 00:05 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/TitleScreen.kt
> +package nextstep.shoppingcart.ui.screen
패키지 이름이 화면에 사용하는거라  ui패키지 하단으로 설정하였고 말그대로 화면에 보여지는 걸 모아 놓으려고 Screen을 붙였습니다. 이전 미션에서도 View보다는 Screen을 사용한다고... 일반적으로 사용하고 있는 부분들이 좀 있을까요? 컴포즈는 아직 많이 부족합니다.

2024-08-16 00:06 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                }
실제 앱을 실행해보고 동작하는 부분까지 확인을 해봤는데요. 이 부분 관련해서는 슬랙으로 다시 문의를 드려보겠습니다.

2024-08-16 04:27 UTC, laco-dev requested changes
DM 남겨주셔서 고맙습니다.

2단계에서 추가해야할 영역이 많기 때문에 1단계에서 챙겨야 할 부분은 마무리 하고 넘어가면 좋을 것 같습니다.

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +        ) {
> 해당 속성은 Column의 height를 유동적으로 변경하기 위해서 사용을 해본건데요. xml의 wrap_content느낌으로요. 무언가 잘못되었을까요?****

fillMaxSize()가 있어서 원래대로라면 이 Column이 전체를 채워야 합니다.
그런데 IntrinsicSize.Min 속성이 들어가면서 우연히 잘 나오게 된 것 같은데요.
높이에 대한 Modifier를 따로 설정하지 않으면, 자연스럽게 유동적으로 늘어나게 됩니다.

아래는 제가 생각한 배치 방법인데 참고 부탁드립니다.
```suggestion
    Column(modifier = modifier) {
        AsyncImage(
            model = product.imageUrl,
            contentDescription = null,
            modifier = Modifier.fillMaxWidth().aspectRatio(1f)
        )
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 4.dp, start = 4.dp)
        ) {
```

```kotlin
ProductItem(
   product = product,
   modifier = Modifier.weight(1f)
)
```

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                fontSize = 16.sp,
회사에서라면 디자인 시스템이 정의되어 있기 떄문에 피그마 시안의 값을 참조하면 고민할 필요가 없어서요.
안써봤으니 어떤 값인지 모르는 것은 자연스러운 것이라서 쓰다보면 자연스럽게 익숙해 질 것 같습니다.

머티리얼도 정리가 되어있는 페이지가 있기는 합니다.
https://m3.material.io/styles/typography/type-scale-tokens

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +}
이슈라기보다는, 단순한 String 포매팅 처리가 가능한데 다소 복잡하게 구현을 하신 것 같아서요

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                color = Color(0xFF333333),
컬러도 비슷하게 MaterialTheme.colorScheme.xxx 형태로 미리 정의된 스타일을 사용할 수 있어요.

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                LazyColumn(modifier = Modifier.padding(top = 13.dp)) {
xml에서 리사이클러뷰의 높이를 만들 때 우리는 wrap_content로 작성하지 않을거에요.
*이건 알고 계실 것이라고 가정합니다.

마찬가지로 LazyColumn에 대해서도 높이가 명확하게 결정되지 않는다면 컨텐츠를 어디까지 그려야 할지 모르게 됩니다.
경우에 따라서는 높이가 결정되지 않았다고 앱이 크래시 나는 경우도 있을 수 있는데요.

이럴때는 명확하게 LazyColumn의 높이를 정해주는 편이 좋습니다.
오류가 안나더라도 스크롤 형태의 UI는 꼭 챙겨줘야 합니다.

```kotlin
LazyColumn(
  modifier = Modifier.fillMaxSize()
   ...
)
```

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                LazyColumn(modifier = Modifier.padding(top = 13.dp)) {
`Modifier.padding(top = 13.dp)` 으로 넣는 것 과 LazyColumn에 contentPadding으로 값을 넣는 것은 어떤 차이가 있을까요??

이 값을 크게 잡아본 뒤, 해당 영역을 스크롤 해 보시면 알 수 있습니다.

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                }
LazyColumn 대신 LazyVerticalGrid를 적용 해보면 어떨까요?
Grid 형태의 UI를 보다 효과적으로 작성할 수 있습니다.

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/TitleScreen.kt
> +package nextstep.shoppingcart.ui.screen
팀마다 회사마다 사람마다 다른 기준입니다....
다만 Screen 같은 경우는 액티비티 뷰모델과 같이 두고는 합니다.
그 외에 컴포넌트는 별도 패키지로 추가하구요

Now In Android, Droid Kaigi, Droid Knights 등의 레퍼런스 앱들을 살펴보세요.

2024-08-16 04:27 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +        ) {
width()를 156으로 고정하면 생길 수 있는 문제점
> 폴드와 같은 화면에서는 오른쪽이 한참 남게 됨
> 만약 가로가 모자라다면 UI가 잘려 보일 수 있음

width()를 고정하게 되는 것에서 weight로 변경하게 되면
--> 아이템이 홀수로 떨어지게 되면 꽉차게 그려져서 이상한 문제가 됨

이는 LazyVerticalGrid를 적용 하거나, 오르쪽을 빈 영역으로 채우는 방법이 있겠습니다.

2024-08-16 05:26 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                fontSize = 16.sp,
디자인 시스템이 적용이 되어있다면 말씀 하신것 처럼 큰 고민 없이 style에 대해서 정의를 하실 필요가 없으실 것 같네요
전 오히려 피그마의 디자인 요소 하나하나를 더 챙겨야 되는 상황에서 개발하다보니 더 그랬던 것 같습니다. 공유주신 내용도 감사합니다.

2024-08-16 05:27 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +}
네 안써보는거 다양한걸 사용해 보려고 해보긴 했습니다. 한줄로 끝나는 부분이긴 하죠

2024-08-16 05:27 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/TitleScreen.kt
> +package nextstep.shoppingcart.ui.screen
언급해 주신 앱들의 레퍼런스 앱을 보고 어떤식으로 구성을 했는지 한번 참고해보도록 하겠습니다.

2024-08-16 05:30 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +        ) {
네 언급주신 내용처럼 폴드와 같은 곳에서는 한참 남게 되겠죠. 사실 이런 경우 가운데 여백을 무게를 두고 나눌 것인지 아니면 이미지 자체를 큰 형식으로 보여줄 것인지에 대한 고민이 필요할 것 같은데요. 사실 피그마만 본 경우에 어떤식으로 구성을 해야 할지 좀 애매한 부분이 있더라고요. 말씀 주신 내용대로라면 weight만 주는 방식으로 해결이 된다로 이해를 하면 될까요? 아 그리고 위에 언급 주신 속성은 제거를 했습니다.

2024-08-16 05:38 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                color = Color(0xFF333333),
영직님 말씀주신 내용에 대해서인데요. 스타일을 적용할 수는 있으나 Figma 요건에 나와있는 항목을 보면 333333이라고 나와있는 부분에 대해서 theme를 사용하려고 하니 같은 속성의 theme가 없는 것 같아서요(이 또한 제가 못찾는 걸수도 있다는 생각이.) 일단 속성이 있는 부분으로 적용은 해보겠습니다.

2024-08-16 05:40 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                LazyColumn(modifier = Modifier.padding(top = 13.dp)) {
속성 값 자체를 정의해 보도록 하겠습니다.

2024-08-16 05:41 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                LazyColumn(modifier = Modifier.padding(top = 13.dp)) {
네 어떤 이야기를 해주시는게 정확히 이해했습니다.

2024-08-16 05:41 UTC, minhyukseul commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductListScreen.kt
> +                }
변경한 걸로 push를 했다고 생각했는데 뭔가 변경 안된 값으로 보고 계신게 아닌가 싶습니다.

2024-08-16 11:29 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +        ) {
여러가지 경우의 수를 고려했을 때 LazyVerticalGrid + weight를 이용한 전략이 가장 적합해 보여서 작성해봤어요.
정답은 물론 여러가지가 있을 수 있겠죠

2024-08-16 11:29 UTC, laco-dev commented on app/src/main/java/nextstep/shoppingcart/ui/screen/ProductItemScreen.kt
> +                color = Color(0xFF333333),
맞아요. 피그마에서 컴포넌트가 연결되지 않으면 나타나지 않습니다.

디자인 시안과 정확히 맞출 필요가 없어서, 적당한 값을 찾는 것을 생각했습니다.

2024-08-16 11:30 UTC, laco-dev approved these changes
좋습니다.

이야기 충분히 나눠본 것 같아서, 다음 미션에서 또 다른 주제로 다뤄보면 좋을 것 같아요.
다음 미션 진행 해주세요 👏🏻

2024-08-16 11:30 UTC, merged